export default {
  index:      { display: 'hidden' },
  'how-deploys-work': 'How Deploys Work',
  create:     'Create Projects & Services',
  methods:    'Deployment Methods',
  templates:  'Templates',
  config:     'Service Configuration',
  manage:     'Project Management',
  networking: 'Networking',

  // ── Hidden: old flat files (now in sub-folders) ──────────────────────────
  'create-project':              { display: 'hidden' },
  'create-service':              { display: 'hidden' },
  dockerfile:                    { display: 'hidden' },
  'custom-docker-image':         { display: 'hidden' },
  'github-integration':          { display: 'hidden' },
  'deploy-button':               { display: 'hidden' },
  'deploy-with-chrome-extension': { display: 'hidden' },
  'deploy-with-vscode-extension': { display: 'hidden' },
  'deploy-with-raycast-extension': { display: 'hidden' },
  'environment-variables':       { display: 'hidden' },
  'root-directory':              { display: 'hidden' },
  'watch-paths':                 { display: 'hidden' },
  'command-execution':           { display: 'hidden' },
  'copy-project':                { display: 'hidden' },
  'export-project':              { display: 'hidden' },
  'migrate-project':             { display: 'hidden' },
  'update-image-reference':      { display: 'hidden' },
  'public-networking':           { display: 'hidden' },
  'private-networking':          { display: 'hidden' },
  'high-availability':           { display: 'hidden' },
}
