export default {
  'how-deploys-work': '部署流程概述',
  create:     '建立專案與服務',
  methods:    '部署方式',
  templates:  { display: 'hidden' },
  config:     '服務設定',
  manage:     '專案管理',
  networking: '網路',

  // ── 隱藏：舊的平面檔案（已搬到子資料夾）──────────────────────────────
  'create-project':              { display: 'hidden' },
  'create-service':              { display: 'hidden' },
  dockerfile:                    { display: 'hidden' },
  'custom-docker-image':         { display: 'hidden' },
  'github-integration':          { display: 'hidden' },
  'deploy-button':               { display: 'hidden' },
  'deploy-with-chrome-extension': { display: 'hidden' },
  'deploy-with-vscode-extension': { display: 'hidden' },
  'deploy-with-raycast-extension': { display: 'hidden' },
  'environment-variables':       { display: 'hidden' },
  'root-directory':              { display: 'hidden' },
  'watch-paths':                 { display: 'hidden' },
  'command-execution':           { display: 'hidden' },
  'copy-project':                { display: 'hidden' },
  'export-project':              { display: 'hidden' },
  'migrate-project':             { display: 'hidden' },
  'update-image-reference':      { display: 'hidden' },
  'public-networking':           { display: 'hidden' },
  'private-networking':          { display: 'hidden' },
  'high-availability':           { display: 'hidden' },
  'large-files':                 { display: 'hidden' },
}
