---
title: Dockerfile 部署
ogImageTitle: Dockerfile 部署
ogImageSubtitle: 藉由 Dockerfile 部署到 Zeabur 上
---

import { Callout } from 'nextra/components'

# Dockerfile 部署

正常情況下你無需自行撰寫 `Dockerfile`，Zeabur 目前已針對各種主流框架提供了快速部署的方式，但如果你的專案不是使用這些框架，或是你想要自行定義部署的方式，你可以使用 `Dockerfile` 來部署。

## 建立 Dockerfile

在你的專案根目錄建立一個名為 `Dockerfile` 或 `dockerfile` 的檔案，並且在裡面撰寫你的部署方式，最後須確保你有暴露對應的 `PORT`。

Zeabur 會自動偵測你的專案是否有 `Dockerfile`，如果有的話會以 docker 的方式來部署你的專案。

<Callout type="info">
  開始部署後即可在上方看到 docker 的圖示，代表你的專案已經以 docker 的方式來部署。
</Callout>

![docker-deploy](/deploy/dockerfile/docker-deploy.png)

## 不使用 Dockerfile 部署

如果你的專案有 Dockerfile，但你不希望在 Zeabur 上使用這個 Dockerfile（例如想由 Zeabur 決定專案最佳的部署方式），你可以在環境變數中設定 `ZBPACK_IGNORE_DOCKERFILE=true`，或在 `zbpack.json` 裡面加入：

```json
{
  "ignore_dockerfile": true
}
```

Zeabur 就會忽略你的 Dockerfile，而由 Zeabur 自動決定部署方式。

## 環境變數

如果你的 `Dockerfile` 需要使用到環境變數，你可以在該服務的頁面點選 **環境變數** 來新增，更多的設定方式請參考 [環境變數](/deploy/variables)。

![環境變數設定](/environment/add-variables.png)

如果你的 `Dockerfile` 撰寫方式為一個階段 (stage)，或是你的環境變數只需在最後一個階段中使用，很好的你無需手動寫 `ENV`，Zeabur 會自動幫你加上。

### ARG

但如果你的 `Dockerfile` 撰寫方式為多個階段 ([multi-stage](https://docs.docker.com/build/building/multi-stage/))，並且需要在建置前就設定環境變數，你可以使用 `ARG` 來設定。

以下我們以 nodejs 及 nginx 為例，撰寫一個 `Dockerfile` 來部署。

```docker {7-8} copy
FROM node:18-alpine AS builder

WORKDIR /app
COPY . .

## 這裡的 `BUILDTIME_ENV_EXAMPLE` 會自動在建置前被設定
ARG BUILDTIME_ENV_EXAMPLE
ENV BUILDTIME_ENV_EXAMPLE=${BUILDTIME_ENV_EXAMPLE}

RUN npm install && \
    npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/configfile.template
COPY --from=builder /app/dist /usr/share/nginx/html

ENV \
    PORT=8080 \
    HOST=0.0.0.0

EXPOSE 8080

CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```

## 指定要部署的 Dockerfile

若想指定要在專案部署的 Dockerfile，請將 Dockerfile 命名為 `[服務名稱].Dockerfile` 或 `Dockerfile.[服務名稱]`。例如，如果你的專案中有一個 `Dockerfile.storage` 檔案，而你的服務名稱是 `storage`，Zeabur 將會使用這個 Dockerfile 來部署 `storage` 服務。

![specify-service-name](/deploy/dockerfile/specify-service-name.png)

您也可以指定 `ZBPACK_DOCKERFILE_NAME` 環境變數，或在 `zbpack.json` 中加入以下內容：

```json
{
  "dockerfile": {
    "name": "storage"
  }
}
```

例如，如果您在服務中設定 `ZBPACK_DOCKERFILE_NAME=storage`，Zeabur 將使用 `Dockerfile.storage` Dockerfile 來部署 `storage` 服務。

## Docker Compose

Zeabur 目前還不支援從 Docker Compose YAML 進行部署。

您可以將 Docker Compose 檔案轉換成 Zeabur Template YAML，可以參考[〈從 YAML 建立模板〉](/template/template-in-code)一文。如果需要協助，也可以在 [社群](https://zeabur.com/forum) 詢問我們。
