export default {
  "create-project": "创建项目",
  "create-service": "创建服务",
  "root-directory": "根目录",
  "watch-paths": "监控路径",
  "command-execution": "命令执行",
  "dockerfile": "Dockerfile 部署",
  "deploy-button": "一键部署按钮",
  "customize-prebuilt": "自定义 Docker 镜像",
  "github": "与 GitHub 集成",
  "deploy-in-cli": "在 CLI 中部署",
  "deploy-with-chrome-extension": "Chrome 扩展部署",
  "deploy-with-vscode-extension": "VS Code 扩展部署",
  "deploy-with-raycast-extension": "Raycast 扩展部署",
  "variables": "环境变量",
  "copy-project": "复制项目",
  "export-project": "导出项目",
  "migrate-project": "迁移项目",
  "update-image-reference": "更新镜像引用",
  "large-files": { display: 'hidden' },
}
