export default {
  index:            { display: 'hidden' },
  'how-deploys-work': '部署原理',
  create:           '创建项目和服务',
  methods:          '部署方式',
  templates:        { display: 'hidden' },
  config:           '服务配置',
  manage:           '项目管理',
  networking:       '网络',

  // ── 隐藏：旧版平铺文件（现已移至子目录）──────────────────────────
  "create-project":              { display: 'hidden' },
  "create-service":              { display: 'hidden' },
  "root-directory":              { display: 'hidden' },
  "watch-paths":                 { display: 'hidden' },
  "command-execution":           { display: 'hidden' },
  "dockerfile":                  { display: 'hidden' },
  "deploy-button":               { display: 'hidden' },
  "customize-prebuilt":          { display: 'hidden' },
  "github":                      { display: 'hidden' },
  "deploy-in-cli":               { display: 'hidden' },
  "deploy-with-chrome-extension": { display: 'hidden' },
  "deploy-with-vscode-extension": { display: 'hidden' },
  "deploy-with-raycast-extension": { display: 'hidden' },
  "variables":                   { display: 'hidden' },
  "copy-project":                { display: 'hidden' },
  "export-project":              { display: 'hidden' },
  "migrate-project":             { display: 'hidden' },
  "update-image-reference":      { display: 'hidden' },
  "large-files":                 { display: 'hidden' },
}
