---
title: Dockerfile 部署
ogImageTitle: Dockerfile 部署
ogImageSubtitle: 藉由 Dockerfile 部署到 Zeabur 上
---

import { Callout } from 'nextra-theme-docs'

# Dockerfile 部署

<Callout>
  這個文章還沒完成，如果你有任何問題，請在 [討論區](https://github.com/orgs/zeabur/discussions) 發問，我們會竭盡全力幫助你。

  如果你想要幫助我們完善文件，請在我們的 [GitHub Repository](https://github.com/zeabur/docs) 上發起 Pull Request。
</Callout>
