---
title: Dockerfile 部署
ogImageTitle: Dockerfile 部署
ogImageSubtitle: 通过 Dockerfile 部署到 Zeabur 上
---

import { Callout } from 'nextra-theme-docs'

# Dockerfile 部署

正常情况下你无需自行撰写 `Dockerfile`，Zeabur 目前已针对各种主流框架提供了快速部署的方式，但如果你的项目不是使用这些框架，或是你想要自行定义部署的方式，你可以使用 `Dockerfile` 来部署。

<Callout type="warning">
  Zeabur 目前仅支持 `Dockerfile` 的部署方式，目前不提供 Docker Compose 的方式。
</Callout>

## 建立 Dockerfile

在你的项目根目录建立一个名为 `Dockerfile` 或 `dockerfile` 的文件，并编辑，最后须确保你有暴露对应的 `PORT`。

Zeabur 会自动检测你的项目是否有 `Dockerfile`，如果有的话会以 Docker 的方式来部署你的项目。

<Callout type="info">
  开始部署后即可在上方看到 Docker 的图标，代表你的项目已经以 Docker 的方式来部署。
</Callout>

![docker-deploy](/deploy/dockerfile/docker-deploy.png)

## 环境变量

如果你的 `Dockerfile` 需要使用到环境变量，你可以在该服务的页面点选 **环境变量** 来新增，更多的设置方式请参考 [环境变量](/zh-CN/environment/variables)。

![环境变量设置](/environment/add-variables.png)

如果你的 `Dockerfile` 只是单阶段 (stage)，或是你的环境变量只需在最后一个阶段中使用，那么你就你无需手动写 `ENV`，Zeabur 会自动帮你加上。

### ARG

但如果你的 `Dockerfile` 使用了多阶段 ([multi-stage](https://docs.docker.com/build/building/multi-stage/)) 特性，并且需要在建置前就设置环境变量，你可以使用 `ARG` 来设置。

以下我们以 nodejs 及 nginx 为例，撰写一个 `Dockerfile` 来部署。

```docker {7-8} copy
FROM node:18-alpine AS builder

WORKDIR /app
COPY . .

## 这里的 BUILDTIME_ENV_EXAMPLE 会自动在建置前被设置
ARG BUILDTIME_ENV_EXAMPLE
ENV BUILDTIME_ENV_EXAMPLE=${BUILDTIME_ENV_EXAMPLE}

RUN npm install && \
    npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/configfile.template
COPY --from=builder /app/dist /usr/share/nginx/html

ENV \
    PORT=8080 \
    HOST=0.0.0.0

EXPOSE 8080

CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```

## 用 Dockerfile 部署特定项目

如果你的 Monorepo 里面有不同项目想分开部署，你可以创建 `Dockerfile.[服务名称]` 并通过服务名称部署指定的 Dockerfile。

以这个案例来说，如果你想部署三个微服务，但都使用同一个 Git Repository，你可以这样命名自己的 Dockerfile：

- `Dockerfile.storage`: 部署 Node.js 的 `storage` 微服务
- `Dockerfile.discord`: 部署 Node.js 的 `discord` 微服务
- `Dockerfile.frontend`: 部署 Next.js 的 `frontend` 前端

然后在 Zeabur 部署你的项目，并到「设置」→「服务名称」中改成你想部署的服务名称，比如 `storage`、`discord` 或 `frontend`：

![specify-service-name](/deploy/dockerfile/specify-service-name.png)

然后点击「Redeploy」重新部署项目，即可部署你想要的服务。你也可以与 [监控路径](./watch-paths) 搭配使用，只在修改相应文件时才触发部署。

## Docker Compose

Zeabur 目前仅支持 `Dockerfile` 的部署方式，目前不提供 Docker Compose 的方式。
