export default {
  "create-service": "Crear Servicio",
  "root-directory": "Directorio Raíz",
  "watch-paths": "Rutas de Vigilancia",
  "command-execution": "Ejecución de Comandos",
  "dockerfile": "Implementar con Dockerfile",
  "deploy-button": "Botón de Implementación",
  "customize-prebuilt": "Personalizar imagen Docker",
  "github": "Integración con GitHub",
  "deploy-in-cli": "Implementar en CLI",
  "deploy-with-chrome-extension": "Implementar con extensión Chrome",
  "deploy-with-vscode-extension": "Implementar con extensión VS Code",
  "deploy-with-raycast-extension": "Implementar con extensión Raycast",
  "variables": "Variables de Entorno",
  "copy-project": "Copiar Proyecto",
  "export-project": "Exportar Proyecto",
  "migrate-project": "Migrar Proyecto",
  "update-image-reference": "Actualizar Referencia de Imagen",
  "large-files": { display: 'hidden' },
}
