export default {
  index:            { display: 'hidden' },
  'how-deploys-work': 'Cómo Funcionan los Despliegues',
  create:           'Crear Proyectos y Servicios',
  methods:          'Métodos de Despliegue',
  templates:        { display: 'hidden' },
  config:           'Configuración de Servicios',
  manage:           'Gestión de Proyectos',
  networking:       'Redes',

  // ── Oculto: archivos planos antiguos (ahora en subcarpetas) ──────────────────────────
  "create-project":              { display: 'hidden' },
  "create-service":              { display: 'hidden' },
  "root-directory":              { display: 'hidden' },
  "watch-paths":                 { display: 'hidden' },
  "command-execution":           { display: 'hidden' },
  "dockerfile":                  { display: 'hidden' },
  "deploy-button":               { display: 'hidden' },
  "customize-prebuilt":          { display: 'hidden' },
  "github":                      { display: 'hidden' },
  "deploy-with-chrome-extension": { display: 'hidden' },
  "deploy-with-vscode-extension": { display: 'hidden' },
  "deploy-with-raycast-extension": { display: 'hidden' },
  "variables":                   { display: 'hidden' },
  "copy-project":                { display: 'hidden' },
  "export-project":              { display: 'hidden' },
  "migrate-project":             { display: 'hidden' },
  "update-image-reference":      { display: 'hidden' },
  "large-files":                 { display: 'hidden' },
  "custom-docker-image":         { display: 'hidden' },
  "github-integration":          { display: 'hidden' },
  "environment-variables":       { display: 'hidden' },
  "high-availability":           { display: 'hidden' },
  "private-networking":          { display: 'hidden' },
  "public-networking":           { display: 'hidden' },
}
