export default {
  index: '基本介绍',
  'get-started': '快速开始',
  deploy: '部署',
  template: '模板',
  marketplace: {
    title: 'Zeabur 模板目录',
    href: 'https://zeabur.com/templates',
  },
  'ai-hub': 'Zeabur AI Hub',
  'data-management': '数据管理',
  networking: '网络',
  guides: '教程',
  manage: '项目管理',
  legal: '法律及政策',
  billing: '付款与账单',
  community: '社区',
  advanced: '高级',
  developer: '开发者',
  "tutorials": "教程",
}
