export default {
  index: 'Introducción',
  'get-started': 'Empezar',
  deploy: 'Implementar',
  template: 'Plantilla',
  marketplace: {
    title: 'Catálogo de Plantillas',
    href: 'https://zeabur.com/templates',
  },
  'ai-hub': 'Zeabur AI Hub',
  'email': 'Zeabur Email',
  'data-management': 'Gestión de Datos',
  networking: 'Redes',
  guides: 'Guías',
  manage: 'Gestión de Proyectos',
  legal: 'Legal y Políticas',
  billing: 'Pagos y Facturación',
  community: 'Comunidad',
  advanced: 'Avanzado',
  developer: 'Desarrollador',
  tutorials: 'Guías de Importación',
}
