export default {
  "create-project": "プロジェクトを作成する",
  "create-service": "サービスの作成",
  "root-directory": "ルートディレクトリ",
  "watch-paths": "監視パス",
  "command-execution": "コマンド実行",
  "dockerfile": "Dockerfile でデプロイ",
  "deploy-button": "デプロイボタン",
  "customize-prebuilt": "カスタム Docker イメージ",
  "github": "GitHub との統合",
  "deploy-in-cli": { display: 'hidden' },
  "deploy-with-chrome-extension": "Chrome 拡張機能でデプロイ",
  "deploy-with-vscode-extension": "VS Code 拡張機能でデプロイ",
  "deploy-with-raycast-extension": "Raycast 拡張機能でデプロイ",
  "variables": "変数",
  "copy-project": "プロジェクトのコピー",
  "export-project": "プロジェクトのエクスポート",
  "migrate-project": "プロジェクトの移行",
  "update-image-reference": "イメージ参照の更新",
  "large-files": { display: 'hidden' },
}
