export default {
  index:            { display: 'hidden' },
  'how-deploys-work': 'デプロイの仕組み',
  create:           'プロジェクトとサービスの作成',
  methods:          'デプロイ方法',
  templates:        { display: 'hidden' },
  config:           'サービス設定',
  manage:           'プロジェクト管理',
  networking:       'ネットワーキング',

  // ── 非表示：旧版フラットファイル（サブフォルダに移動済み）──────────────────────────
  "create-project":              { display: 'hidden' },
  "create-service":              { display: 'hidden' },
  "root-directory":              { display: 'hidden' },
  "watch-paths":                 { display: 'hidden' },
  "command-execution":           { display: 'hidden' },
  "dockerfile":                  { display: 'hidden' },
  "deploy-button":               { display: 'hidden' },
  "customize-prebuilt":          { display: 'hidden' },
  "github":                      { display: 'hidden' },
  "deploy-with-chrome-extension": { display: 'hidden' },
  "deploy-with-vscode-extension": { display: 'hidden' },
  "deploy-with-raycast-extension": { display: 'hidden' },
  "variables":                   { display: 'hidden' },
  "copy-project":                { display: 'hidden' },
  "export-project":              { display: 'hidden' },
  "migrate-project":             { display: 'hidden' },
  "update-image-reference":      { display: 'hidden' },
  "large-files":                 { display: 'hidden' },
  "custom-docker-image":         { display: 'hidden' },
  "github-integration":          { display: 'hidden' },
  "environment-variables":       { display: 'hidden' },
  "high-availability":           { display: 'hidden' },
  "private-networking":          { display: 'hidden' },
  "public-networking":           { display: 'hidden' },
}
