export default {
  index: '基本介紹',
  'get-started': '快速開始',
  deploy: '部署',
  template: '模板',
  marketplace: {
    title: 'Zeabur 模板目錄',
    href: 'https://zeabur.com/templates',
  },
  'ai-hub': 'Zeabur AI Hub',
  'z-send': 'Zeabur Email',
  'data-management': '資料管理',
  networking: '網路',
  guides: '教學',
  manage: '專案管理',
  legal: '法律及政策',
  billing: '付款與帳單',
  community: '社群',
  advanced: '進階',
  developer: '開發者',
  tutorials: "導入指南",
}
