#:schema ./schema.json

id = "actual"
name = "Actual"
description = "A local-first personal finance app"
icon = "https://avatars.githubusercontent.com/u/37879538?s=200&v=4"
tags = ["Finance", "Personal Management"]

[source]
image = "docker.io/actualbudget/actual-server:latest"

[[ports]]
id = "web"
port = 5006
type = "HTTP"

[[volumes]]
id = "data"
dir = "/data"
