#:schema ./schema.json

id = "botway-ce"
name = "Botway CE"
description = "VS Code in the browser, with full packages. Created For Botway Users"
icon = "https://cdn-botway.deno.dev/icons/bwce.svg"

[source]
image = "botwayorg/ce:latest"
command = ["/usr/bin/entrypoint"]

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[[volumes]]
id = "data"
dir = "/root"

[env]
GIT_REPO = { required = true }
GITHUB_TOKEN = { default = "" }
PKGS = { default = "" }
