#:schema ./schema.json

id = "chatgpt-plus-api"
name = "ChatGPT Plus API"
icon = "https://raw.githubusercontent.com/yangjian102621/chatgpt-plus/main/web/public/images/logo.png"
description = "ChatGPT-PLUS 基于 AI 大语言模型 API 实现的 AI 助手全套开源解决方案，自带运营管理后台，开箱即用。集成了 OpenAI, Azure, ChatGLM,讯飞星火，文心一言等多个平台的大语言模型。集成了 MidJourney 和 Stable Diffusion AI绘画功能。"

[source]
image = "registry.cn-shenzhen.aliyuncs.com/geekmaster/chatgpt-plus-api:v4.0.3-amd64"
command = ["/bin/sh"]
args = ["/var/www/app/docker-entrypoint.sh"]

[[ports]]
id = "web"
port = 5678
type = "HTTP"

[[ports]]
id = "executor"
port = 9999
type = "TCP"

[[volumes]]
id = "logs"
dir = "/var/www/app/logs"

[[volumes]]
id = "static"
dir = "/var/www/app/static"

[[volumes]]
id = "leveldb"
dir = "/var/www/app/data"

[[instructions]]
type = "URL"
title = "ChatGPT Plus API Executor Hostname"
content = "${PORT_FORWARDED_HOSTNAME}"
category = "Hostname & Port"

[[instructions]]
type = "PASSWORD"
title = "ChatGPT Plus API Executor Password"
content = "${EXECUTOR_PORT_FORWARDED_PORT}"
category = "Hostname & Port"

[env]
DEBUG = { default = "false" }
LOG_LEVEL = { default = "info" }
CONFIG_FILE = { default = "config.toml" }
JWT_SECRET_KEY = { default = "${PASSWORD}" }

[[configs]]
path = "/var/www/app/docker-entrypoint.sh"
template = """\
set -e

if [ -f /var/www/app/config.toml.inc ]; then
  echo "Build config.toml from config.toml.inc"
  apk add --no-cache envsubst
  cat /var/www/app/config.toml.inc | envsubst | tee /var/www/app/config.toml
fi

/var/www/app/chatgpt-plus-linux
"""

[[configs]]
path = "/var/www/app/config.toml.inc"
template = """\
Listen = "0.0.0.0:5678"
ProxyURL = "" # 如 http://127.0.0.1:7777
MysqlDns = "${MYSQL_USERNAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

[Session]
  SecretKey = "${JWT_SECRET_KEY}" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400

[Redis] # redis 配置信息
  Host = "${REDIS_HOST}"
  Port = ${REDIS_PORT}
  Password = "${REDIS_PASSWORD}"
  DB = 0

[ApiConfig] # 微博热搜，今日头条等函数服务 API 配置，此为第三方插件服务，如需使用请联系作者开通
  ApiURL = ""
  AppId = ""
  Token = ""


[SMS] # Sms 配置，用于发送短信
   Active = "Ali" # 当前启用的短信服务，默认使用阿里云
   [SMS.Bao]
      Username = ""
      Password = ""
      Domain = "api.smsbao.com"
      Sign = "【极客学长】"
      CodeTemplate = "您的验证码是{code}。5分钟有效，若非本人操作，请忽略本短信。"
   [SMS.Ali]
      AccessKey = ""
      AccessSecret = ""
      Product = "Dysmsapi"
      Domain = "dysmsapi.aliyuncs.com"
      Sign = ""
      CodeTempId = ""

[OSS] # OSS 配置，用于存储 MJ 绘画图片
   Active = "LOCAL" # 默认使用本地文件存储引擎
   [OSS.Local]
     BasePath = "./static/upload" # 本地文件上传根路径
     BaseURL = "${ZEABUR_WEB_URL}/static/upload" # 本地上传文件前缀 URL，线上需要把 localhost 替换成自己的实际域名或者IP
   [OSS.Minio]
     Endpoint = "" # 如 172.22.11.200:9000
     AccessKey = "" # 自己去 Minio 控制台去创建一个 Access Key
     AccessSecret = ""
     Bucket = "chatgpt-plus" # 替换为你自己创建的 Bucket，注意要给 Bucket 设置公开的读权限，否则会出现图片无法显示。
     UseSSL = false
     Domain = "" # 地址必须是能够通过公网访问的，否则会出现图片无法显示。
   [OSS.QiNiu] # 七牛云 OSS 配置
       Zone = "z2" # 区域，z0：华东，z1: 华北，na0：北美，as0：新加坡
       AccessKey = ""
       AccessSecret = ""
       Bucket = ""
       Domain = "" # OSS Bucket 所绑定的域名，如 https://img.r9it.com
   [OSS.AliYun]
       Endpoint = "oss-cn-hangzhou.aliyuncs.com"
       AccessKey = ""
       AccessSecret = ""
       Bucket = "chatgpt-plus"
       SubDir = ""
       Domain = ""

[[MjProxyConfigs]]
  Enabled = true
  ApiURL = "http://midjourney-proxy.zeabur.internal:8080"
  ApiKey = "${MIDJOURNEY_PROXY_APISECRET}"

[[MjPlusConfigs]]
  Enabled = false
  ApiURL = "https://api.chat-plus.net"
  Mode = "fast" # MJ 绘画模式，可选值 relax/fast/turbo
  ApiKey = "sk-xxx"

[[SdConfigs]]
  Enabled = false
  ApiURL = ""
  ApiKey = ""
  Txt2ImgJsonPath = "res/sd/text2img.json"

[XXLConfig] # xxl-job 配置，需要你部署 XXL-JOB 定时任务工具，用来定期清理未支付订单和清理过期 VIP，如果你没有启用支付服务，则该服务也无需启动
  Enabled = true # 是否启用 XXL JOB 服务
  ServerAddr = "http://xxl-job-admin.zeabur.internal:8080/xxl-job-admin" # xxl-job-admin 管理地址
  ExecutorIp = "chatgpt-plus-api.zeabur.internal" # 执行器 IP 地址
  ExecutorPort = "9999" # 执行器服务端口
  AccessToken = "${XXL_JOB_EXECUTOR_API_TOKEN}" # 执行器 API 通信 token
  RegistryKey = "chatgpt-plus" # 任务注册 key

[AlipayConfig]
  Enabled = false # 启用支付宝支付通道
  SandBox = false # 是否启用沙盒模式
  UserId = "2088721020750581" # 商户ID
  AppId = "9021000131658023" # App Id
  PrivateKey = "certs/alipay/privateKey.txt" # 应用私钥
  PublicKey = "certs/alipay/appPublicCert.crt" # 应用公钥证书
  AlipayPublicKey = "certs/alipay/alipayPublicCert.crt" # 支付宝公钥证书
  RootCert = "certs/alipay/alipayRootCert.crt" # 支付宝根证书
  NotifyURL = "https://ai.r9it.com/api/payment/alipay/notify" # 支付异步回调地址

[HuPiPayConfig]
  Enabled = false
  Name = "wechat"
  AppId = ""
  AppSecret = ""
  ApiURL = "https://api.xunhupay.com"
  NotifyURL = "https://ai.r9it.com/api/payment/hupipay/notify"

[SmtpConfig] # 注意，阿里云服务器禁用了25号端口，所以如果需要使用邮件功能，请别用阿里云服务器
  Host = "smtp.163.com"
  Port = 25
  AppName = "极客学长"
  From = "test@163.com" # 发件邮箱人地址
  Password = "" #邮箱 stmp 服务授权码

[JPayConfig] # PayJs 支付配置
  Enabled = false
  Name = "wechat" # 请不要改动
  AppId = "" # 商户 ID
  PrivateKey = "" # 秘钥
  ApiURL = "https://payjs.cn"
  NotifyURL = "https://ai.r9it.com/api/payment/payjs/notify" # 异步回调地址，域名改成你自己的
"""
