#:schema ./schema.json

id = "codimd"
name = "CodiMD"
icon = "https://presskit.hackmd.io/Logo/SVG/HackMD_LOGO_vertical_WhiteColor.svg"
description = "Collaborative markdown notes on all platforms."

[[ports]]
id = "app"
port = 3000
type = "HTTP"

[[volumes]]
id = "data"
dir = "/home/hackmd/app/public/uploads"

[source]
image = "nabo.codimd.dev/hackmdio/hackmd:2.5.3"

[env]
CMD_DB_URL = { default = "${POSTGRES_CONNECTION_STRING}" }
CMD_USECDN = { default = "false" }

