#:schema ./schema.json

id = "garnet"
name = "Garnet"
icon = "https://avatars.githubusercontent.com/u/107748533?s=200&v=4"
description = "Garnet is a remote cache-store from Microsoft Research that offers strong performance (throughput and latency), scalability, storage, recovery, cluster sharding, key migration, and replication features. Garnet can work with existing Redis clients."

[source]
image = "zeabur/garnet:v1.0.0"
command = ["/app/GarnetServer"]
args = [
    "-i", "128m",
    "--port", "${GARNET_PORT}",
    "--config-import-path", "/etc/garnet/garnet.conf",
    "--password", "${GARNET_PASSWORD}"
]

[[ports]]
id = "database"
port = 3278
type = "TCP"

[[volumes]]
id = "data"
dir = "/var/lib/garnet"

[[configs]]
path = "/etc/garnet/garnet.conf"
template = """{
	"EnableStorageTier": true,
	"LogDir": "/var/lib/garnet"
}"""

[env]
GARNET_PASSWORD = { default = "${PASSWORD}", expose = true }

GARNET_HOST = { default = "${CONTAINER_HOSTNAME}", expose = true, readonly = true }
GARNET_PORT = { default = "${DATABASE_PORT}", expose = true, readonly = true }

GARNET_CONNECTION_STRING = { default = "redis://:${GARNET_PASSWORD}@${GARNET_HOST}:${GARNET_PORT}", expose = true, readonly = true }
GARNET_URI = { default = "${GARNET_CONNECTION_STRING}", expose = true, readonly = true }

[[instructions]]
type = "TEXT"
title = "Command to connect to your Garnet server"
content = "redis-cli -h ${PORT_FORWARDED_HOSTNAME} -p ${DATABASE_PORT_FORWARDED_PORT} -a ${GARNET_PASSWORD}"

[[instructions]]
type = "PASSWORD"
title = "Garnet password"
content = "${GARNET_PASSWORD}"
category = "Credentials"

[[instructions]]
type = "TEXT"
title = "Garnet host"
content = "${PORT_FORWARDED_HOSTNAME}"
category = "Hostname & Port"

[[instructions]]
type = "TEXT"
title = "Garnet port"
content = "${DATABASE_PORT_FORWARDED_PORT}"
category = "Hostname & Port"
