#:schema ./schema.json

id = "heyform"
name = "Heyform"
icon = "https://icons.zeabur.com/heyform.png"
description = "Build user-focused forms that drive impactful results."
templateURL = "https://zeabur.com/templates/9YAUUO"

[source]
image = "heyform/community-edition:latest"

[[ports]]
id = "web"
port = 8000
type = "HTTP"

[env]
SESSION_KEY = { required = true }
FORM_ENCRYPTION_KEY = { required = true }
APP_HOMEPAGE_URL = { default = "${ZEABUR_WEB_URL}" }
