#:schema ./schema.json

id = "maybe"
name = "Maybe"
icon = "https://avatars.githubusercontent.com/u/80786585"
description = "The OS for your personal finances."

[source]
image = "ghcr.io/maybe-finance/maybe:sha-d240c59d7f715bfad9ede718fbee7c90b5a54f8d"

[[ports]]
id = "web"
port = 3000
type = "HTTP"

[env]
SECRET_KEY_BASE = { default = "${PASSWORD}" }
DB_HOST = { default = "${POSTGRES_HOST}" }
POSTGRES_USER = { default = "${POSTGRES_USERNAME}" }
RAILS_ENV = { default = "production" }
