#:schema ./schema.json

id = "pocketbase"
name = "PocketBase"
description = "PocketBase is an open source backend consisting of embedded database (SQLite) with realtime subscriptions, built-in auth management, convenient dashboard UI and simple REST-ish API."
icon = "https://pocketbase.io/images/logo.svg"

[source]
image = "ghcr.io/muchobien/pocketbase:0.18"

[[ports]]
id = "web"
port = 8090
type = "HTTP"

[[volumes]]
id = "data"
dir = "/pb_data"
