#:schema ./schema.json

id = "rabbitmq"
name = "RabbitMQ"
icon = "https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/rabbitmq.svg"
description = "RabbitMQ is a widely used open-source message broker that implements the Advanced Message Queuing Protocol (AMQP)"
docs = "https://zeabur.com/docs/marketplace/rabbitmq"

[source]
image = "rabbitmq:3-management"

[[ports]]
id = "database"
port = 5672
type = "TCP"

[[ports]]
id = "web"
port = 15672
type = "HTTP"

[[volumes]]
id = "data"
dir = "/var/lib/rabbitmq"

[env]
RABBITMQ_DEFAULT_USER = { default = "admin" }
RABBITMQ_DEFAULT_PASS = { default = "${PASSWORD}" }

RABBITMQ_DEFAULT_VHOST = { default = "/" }

RABBITMQ_HOST = { default = "${CONTAINER_HOSTNAME}", expose = true, readonly = true }
RABBITMQ_PORT = { default = "${DATABASE_PORT}", expose = true, readonly = true }
RABBITMQ_CONNECTION_STRING = { default = "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}", expose = true, readonly = true }
RABBITMQ_URI = { default = "${RABBITMQ_CONNECTION_STRING}", expose = true, readonly = true }

[[instructions]]
type = "TEXT"
title = "RabbitMQ username"
content = "${RABBITMQ_DEFAULT_USER}"
category = "Credentials"

[[instructions]]
type = "PASSWORD"
title = "RabbitMQ password"
content = "${RABBITMQ_DEFAULT_PASS}"
category = "Credentials"

[[instructions]]
type = "TEXT"
title = "RabbitMQ host"
content = "${PORT_FORWARDED_HOSTNAME}"
category = "Hostname & Port"

[[instructions]]
type = "TEXT"
title = "RabbitMQ port"
content = "${DATABASE_PORT_FORWARDED_PORT}"
category = "Hostname & Port"

[[configs]]
path = "/etc/rabbitmq/rabbitmq.conf"
template = """
# Configuration for Rabbit can be found on https://www.rabbitmq.com/docs/configure#config-file
# Reference environment variables by $(ENV_VARIABLE_KEY), for example, "$(ZEABUR_SERVICE_ID)".
"""
