#:schema ./schema.json

id = "supabase-storage"
name = "Supabase Storage API"
description = "Supabase Storage API"
icon = "https://icons.zeabur.com/supabase.png"

[source]
image = "supabase/storage-api:v0.46.4"

[[ports]]
id = "web"
port = 5000
type = "HTTP"

[env]
ENABLE_IMAGE_TRANSFORMATION = { default = "true" }
PGRST_JWT_SECRET = { default = "${JWT_SECRET}" }
AWS_ACCESS_KEY_ID = { default = "${MINIO_USERNAME}" }
AWS_SECRET_ACCESS_KEY = { default = "${MINIO_PASSWORD}" }
ANON_KEY = { default = "${ANON_KEY}" }
FILE_STORAGE_BACKEND_PATH = { default = "/var/lib/storage" }
GLOBAL_S3_ENDPOINT = { default = "http://minio.zeabur.internal:9000" }
REGION = { default = "stub" }
IMGPROXY_URL = { default = "http://imgproxy:5001" }
GLOBAL_S3_PROTOCOL = { default = "http" }
POSTGREST_URL = { default = "http://rest.zeabur.internal:3000" }
SERVICE_KEY = { default = "${SERVICE_ROLE_KEY}" }
FILE_SIZE_LIMIT = { default = "52428800" }
GLOBAL_S3_FORCE_PATH_STYLE = { default = "true" }
TENANT_ID = { default = "stub" }
GLOBAL_S3_BUCKET = { default = "stub" }
STORAGE_BACKEND = { default = "s3" }
AWS_DEFAULT_REGION = { default = "stub" }
DATABASE_URL = { default = "postgres://postgres:${POSTGRES_PASSWORD}@db.zeabur.internal:5432/postgres" }
