#:schema ./schema.json

id = "weaviate"
name = "Weaviate"
icon = "https://avatars.githubusercontent.com/u/37794290"
description = "Weaviate is a cloud-native, open source vector database that is robust, fast, and scalable."
tags = ["Database"]

[source]
image = "semitechnologies/weaviate:1.25.0"

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[[volumes]]
id = "data"
dir = "/var/lib/weaviate"

[env]
AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED = { default = "true" }
QUERY_DEFAULTS_LIMIT = { default = "25" }
PERSISTENCE_DATA_PATH = { default = "/var/lib/weaviate" }
DEFAULT_VECTORIZER_MODULE = { default = "none" }
ENABLE_MODULES = { default = "text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai" }
CLUSTER_HOSTNAME = { default = "node1" }
